BeautyCenter/Models/ProductAndService/AddServiceVm.cs
using BeautyCenter.Common.Types.Dto.ProductsAndServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BeautyCenter.Models.ProductAndService
{
    public class AddServiceVm
    {
        public ServiceDto Service { get; set; }

        public AddServiceVm()
        {
            Service = new ServiceDto();
        }
    }
}

BeautyCenter/Models/ProductAndService/ListServiceVm.cs
using BeautyCenter.Common.Types.Dto.ProductsAndServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BeautyCenter.Models.ProductAndService
{
    public class ListServiceVm
    {
        public List<ServiceDto> Services { get; set; }

        public ListServiceVm()
        {
            Services = new List<ServiceDto>();
        }
    }
}

BeautyCenter/Models/ProductAndService/UpdateServiceVm.cs
using BeautyCenter.Common.Types.Dto.ProductsAndServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BeautyCenter.Models.ProductAndService
{
    public class UpdateServiceVm
    {
        public ServiceDto Service { get; set; }

        public UpdateServiceVm()
        {
            Service = new ServiceDto();
        }
    }
}

BeautyCenter/Controllers/ProductAndService/ProductAndServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BeautyCenter.Business.ProductsAndServices;
using BeautyCenter.Common.Commands.ProductsAndServices;
using BeautyCenter.Models.ProductAndService;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;

namespace BeautyCenter.Controllers
{
    public class ProductAndServiceController : Controller
    {
        private readonly IServiceBusiness serviceBusiness;
        private readonly IToastNotification toastNotificationService;


        public ProductAndServiceController(IServiceBusiness serviceBusiness, IToastNotification toastNotificationService)
        {
            this.serviceBusiness = serviceBusiness;
            this.toastNotificationService = toastNotificationService;
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Service_Add()
        {
            return PartialView("~/Views/ProductAndService/AddServicePartial.cshtml");
        }


        public async Task<ActionResult> Service_Update(int serviceId)
        {
            UpdateServiceVm vm = new UpdateServiceVm();

            var result = await serviceBusiness.GetServiceById(
                        new GetServiceByIdCommand
                        {
                            ServiceId = serviceId
                        });

            if (result.HasError)
            {
                toastNotificationService.AddErrorToastMessage(result.GetErrorMessage());
                return PartialView("~/Views/ProductAndService/UpdateServicePartial.cshtml");
            }


            vm.Service.Id = result.Result.Id;
            vm.Service.Name = result.Result.Name;
            vm.Service.Duration = result.Result.Duration;
            vm.Service.Amount = result.Result.Amount;

            return PartialView("~/Views/ProductAndService/UpdateServicePartial.cshtml",vm);
        }

        [HttpPost]
        public async Task<ActionResult> Service_Update(UpdateServiceVm updateServiceVm)        
        {

            var result = await serviceBusiness.UpdateService(new UpdateServiceCommand
            {
                Service = updateServiceVm.Service
            });

            if (result.HasError)
            {
                toastNotificationService.AddErrorToastMessage(result.GetErrorMessage());
                return View("~/Views/ProductAndService/Index.cshtml");
            }

            toastNotificationService.AddSuccessToastMessage("İşleminiz Başarıyla Gerçekleştirildi");

            return View("~/Views/ProductAndService/Index.cshtml");
        }

        public async Task<ActionResult> Service_Read()
        {

            ListServiceVm customerVm = new ListServiceVm();

            var servicesResult = await serviceBusiness.GetAllServices(new GetAllServicesCommand());

            if (servicesResult.HasError)
            {
                toastNotificationService.AddErrorToastMessage(servicesResult.GetErrorMessage());
                return RedirectToAction("Index", "Home");
            }

            customerVm.Services = servicesResult.Result;

            return Json(customerVm.Services);
        }

        public async Task<ActionResult> Service_Create(AddServiceVm vm)
        {
            var result = await serviceBusiness.SaveService(new SaveServiceCommand
            {
                Service = vm.Service
            });

            if (result.HasError)
            {
                toastNotificationService.AddErrorToastMessage(result.GetErrorMessage());
                return View("~/Views/ProductAndService/Index.cshtml");
            }

            toastNotificationService.AddSuccessToastMessage("İşleminiz Başarıyla Gerçekleştirildi");

            return View("~/Views/ProductAndService/Index.cshtml");
        }

        [AcceptVerbs("Post")]
        public async Task<ActionResult> Service_Delete(int serviceId)
        {
            var result = await serviceBusiness.DeleteService(new DeleteServiceCommand
            {
                ServiceId = serviceId
            });

            if (result.HasError)
            {
                toastNotificationService.AddErrorToastMessage(result.GetErrorMessage());
                return View("~/Views/ProductAndService/Index.cshtml");
            }

            return View("~/Views/ProductAndService/Index.cshtml");
        }
    }
}

BeautyCenter/Views/ProductAndService/AddServicePartial.cshtml
@model BeautyCenter.Models.ProductAndService.AddServiceVm

<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Yeni İşlem</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <div class="m-alert m-alert--icon alert alert-danger m--hide" role="alert" id="m_form_1_msg">
        <div class="m-alert__icon">
            <i class="la la-warning"></i>
        </div>
        <div class="m-alert__text">
            Hay Aksi! Aşağıdaki bilgilerinden bazılarını doldurmayı unutmuş olmalısın.
        </div>
        <div class="m-alert__close">
            <button type="button" class="close" data-close="alert" aria-label="Close"></button>
        </div>
    </div>
    <form id="addNewService" asp-controller="ProductAndService" asp-action="Service_Create" class="m-form m-form--state" method="post">
        <div class="form-group">
            <label for="recipient-name" class="form-control-label">İşlem Adı</label>
            <input asp-for="Service.Name" type="text" class="form-control" id="Name" aria-required="true">
        </div>
        <div class="form-group">
            <label for="message-text" class="form-control-label">İşlem Süresi (Dk)</label>
            <input asp-for="Service.Duration" type="text" class="form-control m-input" id="Duration" aria-required="true">
        </div>
        <div class="form-group">
            <label for="message-text" class="form-control-label">İşlem Ücreti</label>
            <input asp-for="Service.Amount" type="text" class="form-control m-input" id="Amount" aria-required="true">
        </div>
        <div class="form-group">
            <label for="message-text" class="form-control-label">Renk</label>
            <select asp-for="Service.ColorClass" type="text" id="SelectColor" class="form-control" style="width: 100%" aria-required="true">
                <option value="7FFFD4">Aqua</option>
                <option value="71C7EC">Blue</option>
                <option value="FFC0CB">Pink</option>
                <option value="CD00CD">Purple</option>
                <option value="FF0000">Red</option>
                <option value="4169E1">Royal</option>
                <option value="008000">Green</option>                
            </select>
        </div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
    <button id="btnSave" type="submit" class="btn btn-primary">Kaydet</button>
</div>

<script type="text/javascript">
    $(document).ready(function () {

        $('#SelectColor').select2({
            templateResult: formatState,
            placeholder: "Renk Seçiniz...",            
            language: {
                inputTooShort: function () {
                    return 'En az 3 harf giriniz...';
                }
            }
        });

        $("#btnSave").click(function () {
            $("#addNewService").submit();
        });
        ValidateAddNewService();
    });

    function formatState(state) {
        if (!state.id) {
            return state.text;
        }
        var baseUrl = "/lib/theme/assets/demo/demo12/media/images/colorsicon";
        var $state = $(
            '<span><img src="' + baseUrl + '/' + state.element.value.toLowerCase() + '.png" /> ' + state.text + '</span>'
        );
        return $state;
    };

    function ValidateAddNewService() {
        $("#addNewService").validate({
            rules: {
                "Service.Name": {
                    required: true,
                    minlength: 3,
                    maxlength: 20
                },

                "Service.Duration": {
                    required: true,
                    digits: true
                },
                "Service.Amount": {
                    required: true,
                    digits: true
                },
            },

            //display error alert on form submit
            invalidHandler: function (event, validator) {
                mUtil.scrollTo("addNewService", -200);
                var alert = $('#m_form_1_msg');
                alert.removeClass('m--hide').show();
                mUtil.scrollTop();
            },
            messages: {

                "Service.Name": "Lütfen İşlem Adını Giriniz",

                "Service.Duration":"Lütfen İşlem Süresini Giriniz",

                "Service.Amount": "Lütfen İşlem Ücretini Giriniz",
            },
            highlight: function (element) {
                $(element).parent().addClass('has-danger');
            },
            unhighlight: function (element) {
                $(element).parent().removeClass('has-danger');
            }
        });
    }

</script>

BeautyCenter/Views/ProductAndService/Index.cshtml
<div class="m-portlet m-portlet--mobile">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text">
                    İşlemler
                </h3>
            </div>
        </div>
        <div class="m-portlet__head-tools">
            <ul class="m-portlet__nav">
                <li class="m-portlet__nav-item">
                    <a asp-controller="ProductAndService" asp-action="Service_Add" id="newService" class="btn btn-accent m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air" data-toggle="modal" data-target="#m_modal_general">
                        <span>
                            <i class="la la-plus"></i>
                            <span>Yeni İşlem</span>
                        </span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="m-portlet__body">
        <!--begin: Datatable -->
        <table class="table table-striped- table-bordered table-hover table-checkable" id="service_table">
            <thead>
                <tr>
                    <th>İşlem Adı</th>
                    <th>İşlem Süresi (Dk)</th>
                    <th>İşlem Tutarı</th>
                    <th>İşlem Rengi</th>
                    <th>İşlemler</th>

                </tr>
            </thead>
        </table>
    </div>
</div>



<script type="text/javascript">
    $(document).ready(function () {
        $('#service_table').dataTable({
            "ajax": {
                "url": "/ProductAndService/Service_Read/",
                "dataSrc": ""
            },
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Turkish.json",
            },
            "columns": [
                { "data": "Name" },
                { "data": "Duration" },
                {
                    "data": "Amount",
                    "render": function (data, type, row) {
                        return data + ' <i class="fas fa-lira-sign fa-1x"></i>';
                    }
                },
                { "data": "ColorClass" },
                {
                    "data": null,
                    render: function (data, type, row) {
                        return '<a href="#" id="ServiceEdit" onClick = "serviceEdit(' + data.Id + ');" class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill" title="Güncelle" data-toggle="modal" data-target="#m_modal_general"><i class="la la-edit"></i><a href="#" id="ServiceDelete" onClick = "serviceDelete(' + data.Id + ');" class="m-portlet__nav-link btn m-btn m-btn--hover-danger m-btn--icon m-btn--icon-only m-btn--pill" title="Sil"><i class="la la-trash"></i></a>';
                    },
                    "targets": -1
                }
            ]
        });

    });

    function serviceDelete(serviceId) {
        const swalWithBootstrapButtons = Swal.mixin({
            customClass: {
                confirmButton: 'btn btn-danger',
                cancelButton: 'btn btn-secondary'
            },
            buttonsStyling: false,
        })
        swalWithBootstrapButtons.fire({
            title: 'Silmek istediğine emin misin?',
            text: "İşlem tekrar geri alınmayacaktır!",
            type: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Evet, Sil!',
            cancelButtonText: 'Hayır, İptal et!'
        }).then((result) => {
            if (result.value) {
                $.ajax({
                    type: "POST",
                    url: "/ProductAndService/Service_Delete",
                    data: { serviceId: serviceId },
                    cache: false,
                    success: function (response) {
                        Swal.fire(
                            "Başarılı!",
                            "Silme İşleminiz Başarıyla Gerçekleştirilmiştir.",
                            "success"
                        ).then(function () {
                            location.reload();
                        })

                    },
                    failure: function (response) {
                        Swal.fire(
                            "Hata!",
                            "Oops, İşleminizi Gerçekleştirirken Bir Hata Oluştu.", // had a missing comma
                            "error"
                        )
                    }
                })
            }
        } )
    }

    function serviceEdit(serviceId) {
        $.ajax({
            type: "GET",
            url: "/ProductAndService/Service_Update",
            contentType: "application/json; charset=utf-8",
            data: { serviceId: serviceId},
            datatype: "json",
            success: function (data) {
                $('#generalModal').html(data);
            },
            error: function () {
                alert("Dynamic content load failed.");
            }
        });
    }

    $(function () {
        $("#updateCommand").click(function (e) {
            var $buttonClicked = $(this);
            debugger;
            $.ajax({
                type: "GET",
                url: "/ProductAndService/Service_Update",
                contentType: "application/json; charset=utf-8",
                datatype: "json",
                success: function (data) {
                    $('#generalModal').html(data);
                },
                error: function () {
                    alert("Dynamic content load failed.");
                }
            });
        });
    });

    $(function () {
        $("#newService").click(function () {
            debugger;
            var $buttonClicked = $(this);
            $.ajax({
                type: "GET",
                url: "/ProductAndService/Service_Add",
                contentType: "application/json; charset=utf-8",
                datatype: "json",
                success: function (data) {
                    $('#generalModal').html(data);
                },
                error: function () {
                    alert("Dynamic content load failed.");
                }
            });
        });
    });
</script>

BeautyCenter/Views/ProductAndService/UpdateServicePartial.cshtml
@model BeautyCenter.Models.ProductAndService.UpdateServiceVm

<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">İşlem Güncelleme</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <div class="m-alert m-alert--icon alert alert-danger m--hide" role="alert" id="updateFormValidationMessage">
        <div class="m-alert__icon">
            <i class="la la-warning"></i>
        </div>
        <div class="m-alert__text">
            Hay Aksi! Aşağıdaki bilgilerinden bazılarını doldurmayı unutmuş olmalısın.
        </div>
        <div class="m-alert__close">
            <button type="button" class="close" data-close="alert" aria-label="Close"></button>
        </div>
    </div>
    <form id="updateService" asp-controller="ProductAndService" asp-action="Service_Update" class="m-form m-form--state" method="post">
        <input asp-for="Service.Id" type="hidden" id="ServiceId" />
        <div class="form-group">
            <label for="recipient-name" class="form-control-label">İşlem Adı</label>
            <input asp-for="Service.Name" type="text" class="form-control" id="Name" aria-required="true">
        </div>
        <div class="form-group">
            <label for="message-text" class="form-control-label">İşlem Süresi (Dk)</label>
            <input asp-for="Service.Duration" type="text" class="form-control" id="Duration" aria-required="true">
        </div>
        <div class="form-group">
            <label for="message-text" class="form-control-label">İşlem Ücreti</label>
            <input asp-for="Service.Amount" type="text" class="form-control" id="Amount" aria-required="true">
        </div>        
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
    <button id="btnUpdate" type="submit" class="btn btn-primary">Kaydet</button>
</div>

<script type="text/javascript">
    $(document).ready(function () {

        $('#btnUpdate').click(function () {
            $('#updateService').submit();
        })
        ValidateUpdateService();
    })

    function ValidateUpdateService() {
        $('#updateService').validate({
            rules: {
                'Service.Name': {
                    required: true,
                    minlength: 3,
                    maxlength:30
                },
                'Service.Duration': {
                    required: true,
                    digits: true
                },
                'Service.Amount': {
                    required: true,
                    digits: true
                }
            },
            invalidHandler: function (event, validator) {
                mUtil.scrollTo("updateService", -200);
                var alert = $('#updateFormValidationMessage');
                alert.removeClass('m--hide').show();
                mUtil.scrollTop();
            },
            messages: {
                'Service.Name': 'Lütfen İşlem Adını Giriniz',
                'Service.Duration': 'Lütfen İşlem Süresini Giriniz',
                'Service.Amount': 'Lütfen İşlem Ücretini Giriniz'
            },
            highlight: function (element) {
                $(element).parent().addClass('has-danger');
            },
            unhighlight: function (element) {
                $(element).parent().removeClass('has-danger');
            }
        })
    }
</script>